Repository Varsha-1605/SocioSell, pull requests merged in 2025-01, with the labels that each got.

#7 Feature/deselect file icon
  main.py
  static/css/styles.css
  templates/index.html
Labels: enhancement, good first issue, BEGINNER, SWOC

#6 Feature/update navbar icons
  templates/index.html
Labels: enhancement, good first issue, BEGINNER, SWOC

#10 Connected fastAPI to mongoDB, loaded .env variables, added routes & CRUD
  .env
  main.py
  models/analytics.py
  models/analyticsVideo.py
  models/listing.py
  models/product.py
  models/review.py
  models/video.py
  models/videoListing.py
  routers/combined.py
  routers/image.py
  routers/video.py
Labels: enhancement, ADVANCE, SWOC

#28 Implemented Image Request Limiter #22
  routers/image.py
Labels: good first issue, BEGINNER, SWOC, validation, python

#33 Added Health Check Endpoint
  Readme.md
  main.py
Labels: INTERMEDIATE, SWOC, database

#35 feat: added a contributors page to the application with dynamic fetching
  templates/index.html
Labels: enhancement, ADVANCE, SWOC, UI/UX, design

#40 fix: repo commit count via pagination
  templates/index.html
Labels: bug, BEGINNER, SWOC

#36 Index Strategy and Performance Optimization
  database_setup.py
Labels: INTERMEDIATE, SWOC, performance, database, optimization

#43 Docs/improve contributor guides
  Readme.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/PROJECT_STRUCTURE.md
  docs/SECURITY.md
Labels: INTERMEDIATE, SWOC

#47 Update Image Upload Endpoint to Fetch Listings from MongoDB
  schemas/image.py
Labels: ADVANCE, SWOC, database

#49 Enhancements to Video Analysis and Listing Retrieval
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
  database_setup.py
  models/analyticsVideo.py
  models/videoListing.py
  schemas/video.py
Labels: ADVANCE, SWOC, database

#51 Adding Common Meta-Data-error Solution
  Readme.md
Labels: bug, BEGINNER, SWOC

#53 Issue #19
  docs/PROJECT_STRUCTURE.md
  image_processor.py
  main.py
  templates/index.html
  templates/result.html
Labels: high priority, INTERMEDIATE, SWOC, database, integration

#57 Automated Data Insertion for Improved Efficiency
  database_setup.py
  image_data.py
  models/listing.py
  models/product.py
  models/video.py
  schemas/video.py
  video_data.py
Labels: ADVANCE, SWOC, API

#55 Successfully Deployed SocioSell on (Azure VM, Render Platform) and Added Deployment Documentation #39
  Deployment_Documentation.md
  Readme.md
Labels: ADVANCE, SWOC

#45 feat: added connection logging retrying and backoff - mongodb
  database_setup.py
Labels: INTERMEDIATE, SWOC, validation

#59 Add Documentation for Configuring MONGODB_URL in .env File #56
  Readme.md
Labels: documentation, BEGINNER, SWOC

#44 Add MongoDB Connection Pool Monitoring and Health Check
  Readme.md
  main.py
Labels: INTERMEDIATE, SWOC

#62 feat: added deployment ci/cd to reduce downtime possibility
  .github/workflows/keep-alive.yml
Labels: INTERMEDIATE, SWOC

#66 Fix File Upload Conflicts, Improve Navbar Alignment and Responsiveness
  templates/index.html
Labels: bug, ADVANCE, SWOC, validation
