Repository Varsha-1605/SocioSell, pull requests merged in 2025-02, with the labels that each got.

#69 Display All the Generated Listings and Update File Input on File Drop
  templates/index.html
Labels: ADVANCE, SWOC

#70 Update Video Processing Logic & Integration with Upload Route
  main.py
  schemas/video.py
  video_processor.py
Labels: INTERMEDIATE, SWOC

#72 Update swoc links
  Readme.md
Labels: bug, BEGINNER, SWOC
